//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.13 at 11:44:21 AM IST 
//


package com.nordstrom.mlsort.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConnectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConnectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{}NonEmptyStringType"/>
 *         &lt;element name="versionedComponentId" type="{}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bendPoints" type="{}BendPointsType" minOccurs="0"/>
 *         &lt;element name="labelIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="zIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="sourceId" type="{}NonEmptyStringType"/>
 *         &lt;element name="sourceGroupId" type="{}NonEmptyStringType"/>
 *         &lt;element name="sourceType" type="{}NonEmptyStringType"/>
 *         &lt;element name="destinationId" type="{}NonEmptyStringType"/>
 *         &lt;element name="destinationGroupId" type="{}NonEmptyStringType"/>
 *         &lt;element name="destinationType" type="{}NonEmptyStringType"/>
 *         &lt;element name="relationship" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="maxWorkQueueSize" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="maxWorkQueueDataSize" type="{}DataSize" minOccurs="0"/>
 *         &lt;element name="flowFileExpiration" type="{}TimePeriod" minOccurs="0"/>
 *         &lt;element name="queuePrioritizerClass" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectionType", propOrder = {
    "id",
    "versionedComponentId",
    "name",
    "bendPoints",
    "labelIndex",
    "zIndex",
    "sourceId",
    "sourceGroupId",
    "sourceType",
    "destinationId",
    "destinationGroupId",
    "destinationType",
    "relationship",
    "maxWorkQueueSize",
    "maxWorkQueueDataSize",
    "flowFileExpiration",
    "queuePrioritizerClass"
})
public class ConnectionType {

    @XmlElement(required = true)
    protected String id;
    protected String versionedComponentId;
    @XmlElement(required = true)
    protected String name;
    protected BendPointsType bendPoints;
    protected Integer labelIndex;
    protected Integer zIndex;
    @XmlElement(required = true)
    protected String sourceId;
    @XmlElement(required = true)
    protected String sourceGroupId;
    @XmlElement(required = true)
    protected String sourceType;
    @XmlElement(required = true)
    protected String destinationId;
    @XmlElement(required = true)
    protected String destinationGroupId;
    @XmlElement(required = true)
    protected String destinationType;
    @XmlElement(required = true)
    protected List<String> relationship;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxWorkQueueSize;
    protected String maxWorkQueueDataSize;
    protected String flowFileExpiration;
    protected List<String> queuePrioritizerClass;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the versionedComponentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionedComponentId() {
        return versionedComponentId;
    }

    /**
     * Sets the value of the versionedComponentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionedComponentId(String value) {
        this.versionedComponentId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bendPoints property.
     * 
     * @return
     *     possible object is
     *     {@link BendPointsType }
     *     
     */
    public BendPointsType getBendPoints() {
        return bendPoints;
    }

    /**
     * Sets the value of the bendPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link BendPointsType }
     *     
     */
    public void setBendPoints(BendPointsType value) {
        this.bendPoints = value;
    }

    /**
     * Gets the value of the labelIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLabelIndex() {
        return labelIndex;
    }

    /**
     * Sets the value of the labelIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLabelIndex(Integer value) {
        this.labelIndex = value;
    }

    /**
     * Gets the value of the zIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getZIndex() {
        return zIndex;
    }

    /**
     * Sets the value of the zIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setZIndex(Integer value) {
        this.zIndex = value;
    }

    /**
     * Gets the value of the sourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * Sets the value of the sourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceId(String value) {
        this.sourceId = value;
    }

    /**
     * Gets the value of the sourceGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceGroupId() {
        return sourceGroupId;
    }

    /**
     * Sets the value of the sourceGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceGroupId(String value) {
        this.sourceGroupId = value;
    }

    /**
     * Gets the value of the sourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * Sets the value of the sourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceType(String value) {
        this.sourceType = value;
    }

    /**
     * Gets the value of the destinationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationId() {
        return destinationId;
    }

    /**
     * Sets the value of the destinationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationId(String value) {
        this.destinationId = value;
    }

    /**
     * Gets the value of the destinationGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationGroupId() {
        return destinationGroupId;
    }

    /**
     * Sets the value of the destinationGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationGroupId(String value) {
        this.destinationGroupId = value;
    }

    /**
     * Gets the value of the destinationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationType() {
        return destinationType;
    }

    /**
     * Sets the value of the destinationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationType(String value) {
        this.destinationType = value;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRelationship() {
        if (relationship == null) {
            relationship = new ArrayList<String>();
        }
        return this.relationship;
    }

    /**
     * Gets the value of the maxWorkQueueSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxWorkQueueSize() {
        return maxWorkQueueSize;
    }

    /**
     * Sets the value of the maxWorkQueueSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxWorkQueueSize(BigInteger value) {
        this.maxWorkQueueSize = value;
    }

    /**
     * Gets the value of the maxWorkQueueDataSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxWorkQueueDataSize() {
        return maxWorkQueueDataSize;
    }

    /**
     * Sets the value of the maxWorkQueueDataSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxWorkQueueDataSize(String value) {
        this.maxWorkQueueDataSize = value;
    }

    /**
     * Gets the value of the flowFileExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowFileExpiration() {
        return flowFileExpiration;
    }

    /**
     * Sets the value of the flowFileExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowFileExpiration(String value) {
        this.flowFileExpiration = value;
    }

    /**
     * Gets the value of the queuePrioritizerClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queuePrioritizerClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueuePrioritizerClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getQueuePrioritizerClass() {
        if (queuePrioritizerClass == null) {
            queuePrioritizerClass = new ArrayList<String>();
        }
        return this.queuePrioritizerClass;
    }

}
