//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.13 at 11:44:21 AM IST 
//


package com.nordstrom.mlsort.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlowControllerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlowControllerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="maxThreadCount" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *           &lt;sequence>
 *             &lt;element name="maxTimerDrivenThreadCount" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *             &lt;element name="maxEventDrivenThreadCount" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="registries" type="{}RegistriesType" minOccurs="0"/>
 *         &lt;element name="rootGroup" type="{}RootProcessGroupType"/>
 *         &lt;element name="controllerServices" type="{}ControllerServicesType" minOccurs="0"/>
 *         &lt;element name="reportingTasks" type="{}ReportingTasksType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="encoding-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlowControllerType", propOrder = {
    "maxThreadCount",
    "maxTimerDrivenThreadCount",
    "maxEventDrivenThreadCount",
    "registries",
    "rootGroup",
    "controllerServices",
    "reportingTasks"
})
public class FlowControllerType {

    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxThreadCount;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxTimerDrivenThreadCount;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxEventDrivenThreadCount;
    protected RegistriesType registries;
    @XmlElement(required = true)
    protected RootProcessGroupType rootGroup;
    protected ControllerServicesType controllerServices;
    protected ReportingTasksType reportingTasks;
    @XmlAttribute(name = "encoding-version")
    protected String encodingVersion;

    /**
     * Gets the value of the maxThreadCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxThreadCount() {
        return maxThreadCount;
    }

    /**
     * Sets the value of the maxThreadCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxThreadCount(BigInteger value) {
        this.maxThreadCount = value;
    }

    /**
     * Gets the value of the maxTimerDrivenThreadCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxTimerDrivenThreadCount() {
        return maxTimerDrivenThreadCount;
    }

    /**
     * Sets the value of the maxTimerDrivenThreadCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxTimerDrivenThreadCount(BigInteger value) {
        this.maxTimerDrivenThreadCount = value;
    }

    /**
     * Gets the value of the maxEventDrivenThreadCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxEventDrivenThreadCount() {
        return maxEventDrivenThreadCount;
    }

    /**
     * Sets the value of the maxEventDrivenThreadCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxEventDrivenThreadCount(BigInteger value) {
        this.maxEventDrivenThreadCount = value;
    }

    /**
     * Gets the value of the registries property.
     * 
     * @return
     *     possible object is
     *     {@link RegistriesType }
     *     
     */
    public RegistriesType getRegistries() {
        return registries;
    }

    /**
     * Sets the value of the registries property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistriesType }
     *     
     */
    public void setRegistries(RegistriesType value) {
        this.registries = value;
    }

    /**
     * Gets the value of the rootGroup property.
     * 
     * @return
     *     possible object is
     *     {@link RootProcessGroupType }
     *     
     */
    public RootProcessGroupType getRootGroup() {
        return rootGroup;
    }

    /**
     * Sets the value of the rootGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link RootProcessGroupType }
     *     
     */
    public void setRootGroup(RootProcessGroupType value) {
        this.rootGroup = value;
    }

    /**
     * Gets the value of the controllerServices property.
     * 
     * @return
     *     possible object is
     *     {@link ControllerServicesType }
     *     
     */
    public ControllerServicesType getControllerServices() {
        return controllerServices;
    }

    /**
     * Sets the value of the controllerServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControllerServicesType }
     *     
     */
    public void setControllerServices(ControllerServicesType value) {
        this.controllerServices = value;
    }

    /**
     * Gets the value of the reportingTasks property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingTasksType }
     *     
     */
    public ReportingTasksType getReportingTasks() {
        return reportingTasks;
    }

    /**
     * Sets the value of the reportingTasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingTasksType }
     *     
     */
    public void setReportingTasks(ReportingTasksType value) {
        this.reportingTasks = value;
    }

    /**
     * Gets the value of the encodingVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncodingVersion() {
        return encodingVersion;
    }

    /**
     * Sets the value of the encodingVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncodingVersion(String value) {
        this.encodingVersion = value;
    }

}
