//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.13 at 11:44:21 AM IST 
//


package com.nordstrom.mlsort.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PortType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PortType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{}NonEmptyStringType"/>
 *         &lt;element name="versionedComponentId" type="{}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="name" type="{}NonEmptyStringType"/>
 *         &lt;element name="position" type="{}PositionType"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scheduledState" type="{}ScheduledState"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortType", propOrder = {
    "id",
    "versionedComponentId",
    "name",
    "position",
    "comments",
    "scheduledState"
})
@XmlSeeAlso({
    RootGroupPortType.class,
    RemoteGroupPortType.class
})
public class PortType {

    @XmlElement(required = true)
    protected String id;
    protected String versionedComponentId;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected PositionType position;
    @XmlElement(required = true)
    protected String comments;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ScheduledState scheduledState;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the versionedComponentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionedComponentId() {
        return versionedComponentId;
    }

    /**
     * Sets the value of the versionedComponentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionedComponentId(String value) {
        this.versionedComponentId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link PositionType }
     *     
     */
    public PositionType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionType }
     *     
     */
    public void setPosition(PositionType value) {
        this.position = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the scheduledState property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduledState }
     *     
     */
    public ScheduledState getScheduledState() {
        return scheduledState;
    }

    /**
     * Sets the value of the scheduledState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduledState }
     *     
     */
    public void setScheduledState(ScheduledState value) {
        this.scheduledState = value;
    }

}
