//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.13 at 11:44:21 AM IST 
//


package com.nordstrom.mlsort.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{}NonEmptyStringType"/>
 *         &lt;element name="versionedComponentId" type="{}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="name" type="{}NonEmptyStringType"/>
 *         &lt;element name="position" type="{}PositionType"/>
 *         &lt;element name="styles" type="{}Styles"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="class" type="{}NonEmptyStringType"/>
 *         &lt;element name="bundle" type="{}BundleType"/>
 *         &lt;element name="maxConcurrentTasks" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="schedulingPeriod" type="{}NonEmptyStringType"/>
 *         &lt;element name="penalizationPeriod" type="{}TimePeriod"/>
 *         &lt;element name="yieldPeriod" type="{}TimePeriod"/>
 *         &lt;element name="bulletinLevel" type="{}LogLevel"/>
 *         &lt;element name="lossTolerant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="scheduledState" type="{}ScheduledState"/>
 *         &lt;element name="isolated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="schedulingStrategy" type="{}SchedulingStrategy" minOccurs="0"/>
 *         &lt;element name="executionNode" type="{}ExecutionNode" minOccurs="0"/>
 *         &lt;element name="runDurationNanos" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="property" type="{}PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="annotationData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="autoTerminatedRelationship" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessorType", propOrder = {
    "id",
    "versionedComponentId",
    "name",
    "position",
    "styles",
    "comment",
    "clazz",
    "bundle",
    "maxConcurrentTasks",
    "schedulingPeriod",
    "penalizationPeriod",
    "yieldPeriod",
    "bulletinLevel",
    "lossTolerant",
    "scheduledState",
    "isolated",
    "schedulingStrategy",
    "executionNode",
    "runDurationNanos",
    "property",
    "annotationData",
    "autoTerminatedRelationship"
})
public class ProcessorType {

    @XmlElement(required = true)
    protected String id;
    protected String versionedComponentId;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected PositionType position;
    @XmlElement(required = true)
    protected Styles styles;
    protected String comment;
    @XmlElement(name = "class", required = true)
    protected String clazz;
    @XmlElement(required = true)
    protected BundleType bundle;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxConcurrentTasks;
    @XmlElement(required = true)
    protected String schedulingPeriod;
    @XmlElement(required = true)
    protected String penalizationPeriod;
    @XmlElement(required = true)
    protected String yieldPeriod;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LogLevel bulletinLevel;
    protected boolean lossTolerant;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ScheduledState scheduledState;
    protected Boolean isolated;
    @XmlSchemaType(name = "string")
    protected SchedulingStrategy schedulingStrategy;
    @XmlSchemaType(name = "string")
    protected ExecutionNode executionNode;
    protected Long runDurationNanos;
    protected List<PropertyType> property;
    protected String annotationData;
    protected List<String> autoTerminatedRelationship;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the versionedComponentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionedComponentId() {
        return versionedComponentId;
    }

    /**
     * Sets the value of the versionedComponentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionedComponentId(String value) {
        this.versionedComponentId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link PositionType }
     *     
     */
    public PositionType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionType }
     *     
     */
    public void setPosition(PositionType value) {
        this.position = value;
    }

    /**
     * Gets the value of the styles property.
     * 
     * @return
     *     possible object is
     *     {@link Styles }
     *     
     */
    public Styles getStyles() {
        return styles;
    }

    /**
     * Sets the value of the styles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Styles }
     *     
     */
    public void setStyles(Styles value) {
        this.styles = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the bundle property.
     * 
     * @return
     *     possible object is
     *     {@link BundleType }
     *     
     */
    public BundleType getBundle() {
        return bundle;
    }

    /**
     * Sets the value of the bundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleType }
     *     
     */
    public void setBundle(BundleType value) {
        this.bundle = value;
    }

    /**
     * Gets the value of the maxConcurrentTasks property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxConcurrentTasks() {
        return maxConcurrentTasks;
    }

    /**
     * Sets the value of the maxConcurrentTasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxConcurrentTasks(BigInteger value) {
        this.maxConcurrentTasks = value;
    }

    /**
     * Gets the value of the schedulingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulingPeriod() {
        return schedulingPeriod;
    }

    /**
     * Sets the value of the schedulingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulingPeriod(String value) {
        this.schedulingPeriod = value;
    }

    /**
     * Gets the value of the penalizationPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenalizationPeriod() {
        return penalizationPeriod;
    }

    /**
     * Sets the value of the penalizationPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenalizationPeriod(String value) {
        this.penalizationPeriod = value;
    }

    /**
     * Gets the value of the yieldPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYieldPeriod() {
        return yieldPeriod;
    }

    /**
     * Sets the value of the yieldPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYieldPeriod(String value) {
        this.yieldPeriod = value;
    }

    /**
     * Gets the value of the bulletinLevel property.
     * 
     * @return
     *     possible object is
     *     {@link LogLevel }
     *     
     */
    public LogLevel getBulletinLevel() {
        return bulletinLevel;
    }

    /**
     * Sets the value of the bulletinLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogLevel }
     *     
     */
    public void setBulletinLevel(LogLevel value) {
        this.bulletinLevel = value;
    }

    /**
     * Gets the value of the lossTolerant property.
     * 
     */
    public boolean isLossTolerant() {
        return lossTolerant;
    }

    /**
     * Sets the value of the lossTolerant property.
     * 
     */
    public void setLossTolerant(boolean value) {
        this.lossTolerant = value;
    }

    /**
     * Gets the value of the scheduledState property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduledState }
     *     
     */
    public ScheduledState getScheduledState() {
        return scheduledState;
    }

    /**
     * Sets the value of the scheduledState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduledState }
     *     
     */
    public void setScheduledState(ScheduledState value) {
        this.scheduledState = value;
    }

    /**
     * Gets the value of the isolated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsolated() {
        return isolated;
    }

    /**
     * Sets the value of the isolated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsolated(Boolean value) {
        this.isolated = value;
    }

    /**
     * Gets the value of the schedulingStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link SchedulingStrategy }
     *     
     */
    public SchedulingStrategy getSchedulingStrategy() {
        return schedulingStrategy;
    }

    /**
     * Sets the value of the schedulingStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedulingStrategy }
     *     
     */
    public void setSchedulingStrategy(SchedulingStrategy value) {
        this.schedulingStrategy = value;
    }

    /**
     * Gets the value of the executionNode property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutionNode }
     *     
     */
    public ExecutionNode getExecutionNode() {
        return executionNode;
    }

    /**
     * Sets the value of the executionNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutionNode }
     *     
     */
    public void setExecutionNode(ExecutionNode value) {
        this.executionNode = value;
    }

    /**
     * Gets the value of the runDurationNanos property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRunDurationNanos() {
        return runDurationNanos;
    }

    /**
     * Sets the value of the runDurationNanos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRunDurationNanos(Long value) {
        this.runDurationNanos = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * 
     * 
     */
    public List<PropertyType> getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyType>();
        }
        return this.property;
    }

    /**
     * Gets the value of the annotationData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotationData() {
        return annotationData;
    }

    /**
     * Sets the value of the annotationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotationData(String value) {
        this.annotationData = value;
    }

    /**
     * Gets the value of the autoTerminatedRelationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the autoTerminatedRelationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAutoTerminatedRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAutoTerminatedRelationship() {
        if (autoTerminatedRelationship == null) {
            autoTerminatedRelationship = new ArrayList<String>();
        }
        return this.autoTerminatedRelationship;
    }

}
