//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.13 at 11:44:21 AM IST 
//


package com.nordstrom.mlsort.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RemoteGroupPortType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemoteGroupPortType">
 *   &lt;complexContent>
 *     &lt;extension base="{}PortType">
 *       &lt;sequence>
 *         &lt;element name="targetId" type="{}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="maxConcurrentTasks" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="useCompression" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="batchCount" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="batchSize" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="batchDuration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoteGroupPortType", propOrder = {
    "targetId",
    "maxConcurrentTasks",
    "useCompression",
    "batchCount",
    "batchSize",
    "batchDuration"
})
public class RemoteGroupPortType
    extends PortType
{

    protected String targetId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxConcurrentTasks;
    protected boolean useCompression;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger batchCount;
    protected String batchSize;
    protected String batchDuration;

    /**
     * Gets the value of the targetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * Sets the value of the targetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetId(String value) {
        this.targetId = value;
    }

    /**
     * Gets the value of the maxConcurrentTasks property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxConcurrentTasks() {
        return maxConcurrentTasks;
    }

    /**
     * Sets the value of the maxConcurrentTasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxConcurrentTasks(BigInteger value) {
        this.maxConcurrentTasks = value;
    }

    /**
     * Gets the value of the useCompression property.
     * 
     */
    public boolean isUseCompression() {
        return useCompression;
    }

    /**
     * Sets the value of the useCompression property.
     * 
     */
    public void setUseCompression(boolean value) {
        this.useCompression = value;
    }

    /**
     * Gets the value of the batchCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBatchCount() {
        return batchCount;
    }

    /**
     * Sets the value of the batchCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBatchCount(BigInteger value) {
        this.batchCount = value;
    }

    /**
     * Gets the value of the batchSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchSize() {
        return batchSize;
    }

    /**
     * Sets the value of the batchSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchSize(String value) {
        this.batchSize = value;
    }

    /**
     * Gets the value of the batchDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchDuration() {
        return batchDuration;
    }

    /**
     * Sets the value of the batchDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchDuration(String value) {
        this.batchDuration = value;
    }

}
