//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.13 at 11:44:21 AM IST 
//


package com.nordstrom.mlsort.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RootProcessGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RootProcessGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{}NonEmptyStringType"/>
 *         &lt;element name="versionedComponentId" type="{}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="name" type="{}NonEmptyStringType"/>
 *         &lt;element name="position" type="{}PositionType"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processor" type="{}ProcessorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="inputPort" type="{}RootGroupPortType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="outputPort" type="{}RootGroupPortType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="label" type="{}LabelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="funnel" type="{}FunnelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="processGroup" type="{}ProcessGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="remoteProcessGroup" type="{}RemoteProcessGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="connection" type="{}ConnectionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="controllerService" type="{}ControllerServiceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="template" type="{}TemplateType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RootProcessGroupType", propOrder = {
    "id",
    "versionedComponentId",
    "name",
    "position",
    "comment",
    "processor",
    "inputPort",
    "outputPort",
    "label",
    "funnel",
    "processGroup",
    "remoteProcessGroup",
    "connection",
    "controllerService",
    "template"
})
public class RootProcessGroupType {

    @XmlElement(required = true)
    protected String id;
    protected String versionedComponentId;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected PositionType position;
    @XmlElement(required = true)
    protected String comment;
    protected List<ProcessorType> processor;
    protected List<RootGroupPortType> inputPort;
    protected List<RootGroupPortType> outputPort;
    protected List<LabelType> label;
    protected List<FunnelType> funnel;
    protected List<ProcessGroupType> processGroup;
    protected List<RemoteProcessGroupType> remoteProcessGroup;
    protected List<ConnectionType> connection;
    protected List<ControllerServiceType> controllerService;
    protected List<TemplateType> template;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the versionedComponentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionedComponentId() {
        return versionedComponentId;
    }

    /**
     * Sets the value of the versionedComponentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionedComponentId(String value) {
        this.versionedComponentId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link PositionType }
     *     
     */
    public PositionType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionType }
     *     
     */
    public void setPosition(PositionType value) {
        this.position = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the processor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessorType }
     * 
     * 
     */
    public List<ProcessorType> getProcessor() {
        if (processor == null) {
            processor = new ArrayList<ProcessorType>();
        }
        return this.processor;
    }

    /**
     * Gets the value of the inputPort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputPort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputPort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RootGroupPortType }
     * 
     * 
     */
    public List<RootGroupPortType> getInputPort() {
        if (inputPort == null) {
            inputPort = new ArrayList<RootGroupPortType>();
        }
        return this.inputPort;
    }

    /**
     * Gets the value of the outputPort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputPort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputPort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RootGroupPortType }
     * 
     * 
     */
    public List<RootGroupPortType> getOutputPort() {
        if (outputPort == null) {
            outputPort = new ArrayList<RootGroupPortType>();
        }
        return this.outputPort;
    }

    /**
     * Gets the value of the label property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the label property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelType }
     * 
     * 
     */
    public List<LabelType> getLabel() {
        if (label == null) {
            label = new ArrayList<LabelType>();
        }
        return this.label;
    }

    /**
     * Gets the value of the funnel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the funnel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFunnel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FunnelType }
     * 
     * 
     */
    public List<FunnelType> getFunnel() {
        if (funnel == null) {
            funnel = new ArrayList<FunnelType>();
        }
        return this.funnel;
    }

    /**
     * Gets the value of the processGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessGroupType }
     * 
     * 
     */
    public List<ProcessGroupType> getProcessGroup() {
        if (processGroup == null) {
            processGroup = new ArrayList<ProcessGroupType>();
        }
        return this.processGroup;
    }

    /**
     * Gets the value of the remoteProcessGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remoteProcessGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemoteProcessGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RemoteProcessGroupType }
     * 
     * 
     */
    public List<RemoteProcessGroupType> getRemoteProcessGroup() {
        if (remoteProcessGroup == null) {
            remoteProcessGroup = new ArrayList<RemoteProcessGroupType>();
        }
        return this.remoteProcessGroup;
    }

    /**
     * Gets the value of the connection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConnectionType }
     * 
     * 
     */
    public List<ConnectionType> getConnection() {
        if (connection == null) {
            connection = new ArrayList<ConnectionType>();
        }
        return this.connection;
    }

    /**
     * Gets the value of the controllerService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controllerService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControllerService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControllerServiceType }
     * 
     * 
     */
    public List<ControllerServiceType> getControllerService() {
        if (controllerService == null) {
            controllerService = new ArrayList<ControllerServiceType>();
        }
        return this.controllerService;
    }

    /**
     * Gets the value of the template property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the template property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemplateType }
     * 
     * 
     */
    public List<TemplateType> getTemplate() {
        if (template == null) {
            template = new ArrayList<TemplateType>();
        }
        return this.template;
    }

}
