//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.13 at 11:44:21 AM IST 
//


package com.nordstrom.mlsort.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchedulingStrategy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SchedulingStrategy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EVENT_DRIVEN"/>
 *     &lt;enumeration value="TIMER_DRIVEN"/>
 *     &lt;enumeration value="PRIMARY_NODE_ONLY"/>
 *     &lt;enumeration value="CRON_DRIVEN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SchedulingStrategy")
@XmlEnum
public enum SchedulingStrategy {

    EVENT_DRIVEN,
    TIMER_DRIVEN,
    PRIMARY_NODE_ONLY,
    CRON_DRIVEN;

    public String value() {
        return name();
    }

    public static SchedulingStrategy fromValue(String v) {
        return valueOf(v);
    }

}
