//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.13 at 11:44:21 AM IST 
//


package com.nordstrom.mlsort.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VersionControlInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VersionControlInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="registryId" type="{}NonEmptyStringType"/>
 *         &lt;element name="bucketId" type="{}NonEmptyStringType"/>
 *         &lt;element name="bucketName" type="{}NonEmptyStringType"/>
 *         &lt;element name="flowId" type="{}NonEmptyStringType"/>
 *         &lt;element name="flowName" type="{}NonEmptyStringType"/>
 *         &lt;element name="flowDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{}NonEmptyStringType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VersionControlInformation", propOrder = {
    "registryId",
    "bucketId",
    "bucketName",
    "flowId",
    "flowName",
    "flowDescription",
    "version"
})
public class VersionControlInformation {

    @XmlElement(required = true)
    protected String registryId;
    @XmlElement(required = true)
    protected String bucketId;
    @XmlElement(required = true)
    protected String bucketName;
    @XmlElement(required = true)
    protected String flowId;
    @XmlElement(required = true)
    protected String flowName;
    @XmlElement(required = true)
    protected String flowDescription;
    @XmlElement(required = true)
    protected String version;

    /**
     * Gets the value of the registryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistryId() {
        return registryId;
    }

    /**
     * Sets the value of the registryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistryId(String value) {
        this.registryId = value;
    }

    /**
     * Gets the value of the bucketId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBucketId() {
        return bucketId;
    }

    /**
     * Sets the value of the bucketId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBucketId(String value) {
        this.bucketId = value;
    }

    /**
     * Gets the value of the bucketName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBucketName() {
        return bucketName;
    }

    /**
     * Sets the value of the bucketName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBucketName(String value) {
        this.bucketName = value;
    }

    /**
     * Gets the value of the flowId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowId() {
        return flowId;
    }

    /**
     * Sets the value of the flowId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowId(String value) {
        this.flowId = value;
    }

    /**
     * Gets the value of the flowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowName() {
        return flowName;
    }

    /**
     * Sets the value of the flowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowName(String value) {
        this.flowName = value;
    }

    /**
     * Gets the value of the flowDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowDescription() {
        return flowDescription;
    }

    /**
     * Sets the value of the flowDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowDescription(String value) {
        this.flowDescription = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
